version: "3.1"

services:
  nosql:
    container_name: warren_database
    image: mongo
    user: root
    environment:
      - MONGO_INITDB_ROOT_USERNAME=warren
      - MONGO_INITDB_ROOT_PASSWORD=warren
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./data/nosql:/data/db